# theme: jekyll-theme-minimal
# title: ECE 5160 Fast Robots
# description: Website for Lab Reports

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ECE 5160 Fast Robots
description: Website for Lab Reports
